### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by jpily** [steve-community/steve#1057]
Build successfully and java-jar target/steve.I ran through jar but failed to start. Help me.

The configuration requirements are as follows
1. jdk - 11.0.17 (oracle)
2. meven install and Environment variable setting completed 
3. steve-master / mvn package completed (build)
4. java-jar target/steve failed

-----------------------log------------------------------------------------------------------------------------------------------
[INFO ] 2023-02-15 18:23:25,280 de.rwth.idsg.steve.utils.PropertiesFileLoader - Hint: The Java system property 'main.properties' can be set to point to an external properties file, which will be prioritized over the bundled one
[INFO ] 2023-02-15 18:23:25,453 de.rwth.idsg.steve.Application - Loaded the properties. Starting with the 'PROD' profile
[INFO ] 2023-02-15 18:23:25,465 de.rwth.idsg.steve.Application - Date/time zone of the application is set to UTC. Current date/time: 2023-02-15T09:23:25.457Z
[INFO ] 2023-02-15 18:23:25,618 org.eclipse.jetty.server.Server - jetty-10.0.13; built: 2022-12-07T20:13:20.134Z; git: 1c2636ea05c0ca8de1ffd6ca7f3a98ac084c766d; jvm 19.0.2+7-44
[INFO ] 2023-02-15 18:23:25,751 org.eclipse.jetty.server.handler.ContextHandler.steve - No Spring WebApplicationInitializer types detected on classpath
[INFO ] 2023-02-15 18:23:25,756 org.eclipse.jetty.server.session.DefaultSessionIdManager - Session workerName=node0
[INFO ] 2023-02-15 18:23:25,764 org.eclipse.jetty.server.handler.ContextHandler.steve - Initializing Spring root WebApplicationContext
[INFO ] 2023-02-15 18:23:25,765 org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization started
[INFO ] 2023-02-15 18:23:26,497 com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
[INFO ] 2023-02-15 18:23:26,800 com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@6b6def36
[INFO ] 2023-02-15 18:23:26,801 com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
[INFO ] 2023-02-15 18:23:28,859 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2010/08/}CentralSystemService from class ocpp.cs._2010._08.CentralSystemService
[INFO ] 2023-02-15 18:23:29,212 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemServiceOCPP12
[INFO ] 2023-02-15 18:23:29,221 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2012/06/}CentralSystemService from class ocpp.cs._2012._06.CentralSystemService
[INFO ] 2023-02-15 18:23:29,259 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemServiceOCPP15
[INFO ] 2023-02-15 18:23:29,260 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2015/10/}CentralSystemService from class ocpp.cs._2015._10.CentralSystemService
[INFO ] 2023-02-15 18:23:29,288 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemServiceOCPP16
[INFO ] 2023-02-15 18:23:29,289 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean - Creating Service {urn://Ocpp/Cs/2010/08/}CentralSystemService from class ocpp.cs._2010._08.CentralSystemService
[INFO ] 2023-02-15 18:23:29,293 org.apache.cxf.endpoint.ServerImpl - Setting the server's publish address to be /CentralSystemService
[INFO ] 2023-02-15 18:23:33,840 org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 6.1.7.Final
[INFO ] 2023-02-15 18:23:34,104 org.springframework.security.web.DefaultSecurityFilterChain - Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@1b52f723, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@39384ba6, org.springframework.security.web.context.SecurityContextPersistenceFilter@3b6d94fc, org.springframework.security.web.header.HeaderWriterFilter@4d992634, org.springframework.security.web.csrf.CsrfFilter@62c019bb, org.springframework.security.web.authentication.logout.LogoutFilter@570f96b7, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@2116e9cf, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@665fb1d8, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@1272f6d9, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@e7529ac, org.springframework.security.web.session.SessionManagementFilter@3a7e13c0, org.springframework.security.web.access.ExceptionTranslationFilter@2c3762c7, org.springframework.security.web.access.intercept.AuthorizationFilter@7475f071]
[INFO ] 2023-02-15 18:23:34,125 org.springframework.security.web.DefaultSecurityFilterChain - Will secure Ant [pattern='/api/**'] with [org.springframework.security.web.session.DisableEncodeUrlFilter@5748638c, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@7e864a8c, org.springframework.security.web.context.SecurityContextPersistenceFilter@4bba628, org.springframework.security.web.header.HeaderWriterFilter@59b5251d, org.springframework.security.web.authentication.logout.LogoutFilter@5a98983b, de.rwth.idsg.steve.config.SecurityConfiguration$ApiKeyFilter@5e60e639, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@344db28d, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@4420f4d4, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@6bab65b6, org.springframework.security.web.session.SessionManagementFilter@1098c1b1, org.springframework.security.web.access.ExceptionTranslationFilter@3ad142f0, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@56394880]
[WARN ] 2023-02-15 18:23:34,127 org.springframework.security.config.annotation.web.builders.WebSecurity - You are asking Spring Security to ignore Ant [pattern='/static/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
[INFO ] 2023-02-15 18:23:34,127 org.springframework.security.web.DefaultSecurityFilterChain - Will not secure Ant [pattern='/static/**']
[WARN ] 2023-02-15 18:23:34,127 org.springframework.security.config.annotation.web.builders.WebSecurity - You are asking Spring Security to ignore Ant [pattern='/services/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
[INFO ] 2023-02-15 18:23:34,128 org.springframework.security.web.DefaultSecurityFilterChain - Will not secure Ant [pattern='/services/**']
[ERROR] 2023-02-15 18:23:34,542 org.springframework.web.context.ContextLoader - Context initialization failed
de.rwth.idsg.steve.SteveException: MySQL and Java are not using the same time zone. Java offset in seconds (0) != MySQL offset in seconds (32400)
	at de.rwth.idsg.steve.utils.DateTimeUtils.checkJavaAndMySQLOffsets(DateTimeUtils.java:109) ~[steve.jar:?]
	at de.rwth.idsg.steve.config.BeanConfiguration.afterStart(BeanConfiguration.java:181) ~[steve.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) ~[spring-web-5.3.23.jar:5.3.23]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1048) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:983) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:740) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304) ~[jetty-webapp-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:900) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532) ~[jetty-webapp-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:221) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.Server.start(Server.java:470) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.Server.doStart(Server.java:415) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at de.rwth.idsg.steve.JettyServer.start(JettyServer.java:168) ~[steve.jar:?]
	at de.rwth.idsg.steve.SteveProdStarter.start(SteveProdStarter.java:55) ~[steve.jar:?]
	at de.rwth.idsg.steve.Application.start(Application.java:75) ~[steve.jar:?]
	at de.rwth.idsg.steve.Application.main(Application.java:64) ~[steve.jar:?]
[WARN ] 2023-02-15 18:23:34,543 org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@4152d38d{/steve,jar:file:/E:/JDH/01_Products/12_EV_Charger/OCCP_TEST/OCPP_STeveServer/steve-master/steve-master/target/steve.jar!/webapp,UNAVAILABLE}
de.rwth.idsg.steve.SteveException: MySQL and Java are not using the same time zone. Java offset in seconds (0) != MySQL offset in seconds (32400)
	at de.rwth.idsg.steve.utils.DateTimeUtils.checkJavaAndMySQLOffsets(DateTimeUtils.java:109) ~[steve.jar:?]
	at de.rwth.idsg.steve.config.BeanConfiguration.afterStart(BeanConfiguration.java:181) ~[steve.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) ~[spring-web-5.3.23.jar:5.3.23]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1048) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:983) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:740) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304) ~[jetty-webapp-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:900) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532) ~[jetty-webapp-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:221) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.Server.start(Server.java:470) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.Server.doStart(Server.java:415) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at de.rwth.idsg.steve.JettyServer.start(JettyServer.java:168) ~[steve.jar:?]
	at de.rwth.idsg.steve.SteveProdStarter.start(SteveProdStarter.java:55) ~[steve.jar:?]
	at de.rwth.idsg.steve.Application.start(Application.java:75) ~[steve.jar:?]
	at de.rwth.idsg.steve.Application.main(Application.java:64) ~[steve.jar:?]
[ERROR] 2023-02-15 18:23:34,546 de.rwth.idsg.steve.SteveProdStarter - Exception happened
de.rwth.idsg.steve.SteveException: MySQL and Java are not using the same time zone. Java offset in seconds (0) != MySQL offset in seconds (32400)
	at de.rwth.idsg.steve.utils.DateTimeUtils.checkJavaAndMySQLOffsets(DateTimeUtils.java:109) ~[steve.jar:?]
	at de.rwth.idsg.steve.config.BeanConfiguration.afterStart(BeanConfiguration.java:181) ~[steve.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292) ~[spring-web-5.3.23.jar:5.3.23]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) ~[spring-web-5.3.23.jar:5.3.23]
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:1048) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:624) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.ContextHandler.contextInitialized(ContextHandler.java:983) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:740) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:392) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1304) ~[jetty-webapp-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:900) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306) ~[jetty-servlet-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:532) ~[jetty-webapp-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:221) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:121) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.Server.start(Server.java:470) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[jetty-util-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.server.Server.doStart(Server.java:415) ~[jetty-server-10.0.13.jar:10.0.13]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[jetty-util-10.0.13.jar:10.0.13]
	at de.rwth.idsg.steve.JettyServer.start(JettyServer.java:168) ~[steve.jar:?]
	at de.rwth.idsg.steve.SteveProdStarter.start(SteveProdStarter.java:55) ~[steve.jar:?]
	at de.rwth.idsg.steve.Application.start(Application.java:75) ~[steve.jar:?]
	at de.rwth.idsg.steve.Application.main(Application.java:64) ~[steve.jar:?]
[INFO ] 2023-02-15 18:23:34,547 org.eclipse.jetty.server.Server - Stopped Server@107ed6fc{STOPPING}[10.0.13,sto=5000]
[INFO ] 2023-02-15 18:23:34,547 org.eclipse.jetty.server.Server - Shutdown Server@107ed6fc{STOPPING}[10.0.13,sto=5000]
[INFO ] 2023-02-15 18:23:34,555 org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@4152d38d{/steve,jar:file:/E:/JDH/01_Products/12_EV_Charger/OCCP_TEST/OCPP_STeveServer/steve-master/steve-master/target/steve.jar!/webapp,STOPPED}

**Comment by goekay** [comment]
see https://github.com/steve-community/steve/wiki/FAQ#how-to-fix-the-exception-mysql-and-java-are-not-using-the-same-time-zone
