### ISSUE TITLE
Unable to start SteVe 3.6.0 via Docker

### ISSUE THREAD

**Issue by lokipo** [steve-community/steve#1402]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : 3.6.0
Operating system  : Ubuntu 22 / Docker
JDK               :  clipse-temurin:17-jdk
Database          :  mariadb:10.4.30
```

#### Expected Behavior

SteVe starting

#### Actual Behavior

app_1  | [INFO] --- jar:3.3.0:jar (default-jar) @ steve ---
app_1  | [INFO] Building jar: /code/target/steve.jar
app_1  | [INFO] ------------------------------------------------------------------------
app_1  | [INFO] BUILD SUCCESS
app_1  | [INFO] ------------------------------------------------------------------------
app_1  | [INFO] Total time:  31.170 s
app_1  | [INFO] Finished at: 2024-03-08T19:35:22Z
app_1  | [INFO] ------------------------------------------------------------------------
app_1  | [WARNING] 
app_1  | [WARNING] Plugin validation issues were detected in 1 plugin(s)
app_1  | [WARNING] 
app_1  | [WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
app_1  | [WARNING] 
app_1  | [WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
app_1  | [WARNING] 
app_1  | [INFO ] 2024-03-08 19:35:25,041 de.rwth.idsg.steve.utils.PropertiesFileLoader (main) - Hint: The Java system property 'main.properties' can be set to point to an external properties file, which will be prioritized over the bundled one
app_1  | [INFO ] 2024-03-08 19:35:25,187 de.rwth.idsg.steve.Application (main) - Loaded the properties. Starting with the 'PROD' profile
app_1  | [INFO ] 2024-03-08 19:35:25,207 de.rwth.idsg.steve.Application (main) - Date/time zone of the application is set to UTC. Current date/time: 2024-03-08T19:35:25.194Z
app_1  | Log file: Not available
app_1  | Starting.[INFO ] 2024-03-08 19:35:25,449 org.eclipse.jetty.server.Server (main) - jetty-10.0.14; built: 2023-02-22T23:12:32.272Z; git: 976721d0f3e903a243584d47870ad2f2c1bf9e55; jvm 17.0.10+7
app_1  |  FAILED!
app_1  | Please refer to the log file for details
app_1  | Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.IllegalStateException: STOPPED
app_1  | 	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
app_1  | 	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
app_1  | 	at org.eclipse.jetty.server.Server.doStop(Server.java:490)
app_1  | 	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:132)
app_1  | 	at de.rwth.idsg.steve.JettyServer.stop(JettyServer.java:185)
app_1  | 	at de.rwth.idsg.steve.SteveProdStarter.stop(SteveProdStarter.java:80)
app_1  | 	at de.rwth.idsg.steve.Application.stop(Application.java:86)
app_1  | 	at de.rwth.idsg.steve.Application.main(Application.java:69)
app_1  | Caused by: java.lang.IllegalStateException: STOPPED
app_1  | 	at org.eclipse.jetty.server.handler.ContextHandler.shutdown(ContextHandler.java:774)
app_1  | 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
app_1  | 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
app_1  | 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
app_1  | 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
app_1  | 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
app_1  | 	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
app_1  | 	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
app_1  | 	at org.eclipse.jetty.util.component.Graceful.shutdown(Graceful.java:146)
app_1  | 	... 6 more
steve_app_1 exited with code 1

#### Steps to Reproduce the Problem

  1. Build Docker-Container and run

#### Additional context

...

**Comment by AffiTheCreator** [comment]
same issue here

**Comment by lokipo** [comment]
Master is broken, just download the latest release.

**Comment by goekay** [comment]
fresh checkout of HEAD and running the following without modifications:

```
% docker-compose up -d                                      
[+] Running 10/10
 ✔ db 9 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                                                                                                                                                                                                                 14.6s 
   ✔ edab87ea811e Pull complete                                                                                                                                                                                                                                                                                                                                                                    3.4s 
   ✔ 2284a6434f56 Pull complete                                                                                                                                                                                                                                                                                                                                                                    0.7s 
   ✔ cb060ede2339 Pull complete                                                                                                                                                                                                                                                                                                                                                                    2.8s 
   ✔ 19ed949feb53 Pull complete                                                                                                                                                                                                                                                                                                                                                                    1.9s 
   ✔ a4d27c3f410f Pull complete                                                                                                                                                                                                                                                                                                                                                                    2.8s 
   ✔ d1ac8464c9d6 Pull complete                                                                                                                                                                                                                                                                                                                                                                   10.0s 
   ✔ 3da69c4cc166 Pull complete                                                                                                                                                                                                                                                                                                                                                                    3.5s 
   ✔ e72f0cf34cfe Pull complete                                                                                                                                                                                                                                                                                                                                                                    4.8s 
   ✔ 83cd48be7eb3 Pull complete                                                                                                                                                                                                                                                                                                                                                                    4.4s 
[+] Building 3.2s (9/9) FINISHED                                                                                                                                                                                                                                                                                                                                                         docker:default
 => [app internal] load build definition from Dockerfile                                                                                                                                                                                                                                                                                                                                           0.0s
 => => transferring dockerfile: 859B                                                                                                                                                                                                                                                                                                                                                               0.0s
 => [app internal] load .dockerignore                                                                                                                                                                                                                                                                                                                                                              0.0s
 => => transferring context: 2B                                                                                                                                                                                                                                                                                                                                                                    0.0s
 => [app internal] load metadata for docker.io/library/eclipse-temurin:17-jdk                                                                                                                                                                                                                                                                                                                      1.0s
 => [app 1/4] FROM docker.io/library/eclipse-temurin:17-jdk@sha256:930303097744dec5f45d4ba4e3084dbec826f01a44ebb4303971afb112397a3e                                                                                                                                                                                                                                                                0.0s
 => [app internal] load build context                                                                                                                                                                                                                                                                                                                                                              0.9s
 => => transferring context: 58.91MB                                                                                                                                                                                                                                                                                                                                                               0.8s
 => CACHED [app 2/4] RUN curl -sfL https://github.com/powerman/dockerize/releases/download/"v0.19.0"/dockerize-`uname -s`-`uname -m` | install /dev/stdin /usr/local/bin/dockerize                                                                                                                                                                                                                 0.0s
 => CACHED [app 3/4] WORKDIR /code                                                                                                                                                                                                                                                                                                                                                                 0.0s
 => [app 4/4] COPY . /code                                                                                                                                                                                                                                                                                                                                                                         0.9s
 => [app] exporting to image                                                                                                                                                                                                                                                                                                                                                                       0.4s
 => => exporting layers                                                                                                                                                                                                                                                                                                                                                                            0.3s
 => => writing image sha256:543f9378ae77c6d46a9177a348e6127ff5a24d6fc6c127a0bd5b1c793fa99876                                                                                                                                                                                                                                                                                                       0.0s
 => => naming to docker.io/library/steve-app                                                                                                                                                                                                                                                                                                                                                       0.0s
[+] Running 2/2
 ✔ Container steve-db-1   Started                                                                                                                                                                                                                                                                                                                                                                  0.0s 
 ✔ Container steve-app-1  Started   
```

and then
```
% docker container logs steve-app-1 

... (redaction: omitted mvn build logs)...

[INFO] Building jar: /code/target/steve.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:19 min
[INFO] Finished at: 2024-04-25T11:37:33Z
[INFO] ------------------------------------------------------------------------
[WARNING] 
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING] 
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING] 
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING] 
[INFO ] 2024-04-25 11:37:36,736 de.rwth.idsg.steve.utils.PropertiesFileLoader (main) - Hint: The Java system property 'main.properties' can be set to point to an external properties file, which will be prioritized over the bundled one
[INFO ] 2024-04-25 11:37:36,878 de.rwth.idsg.steve.Application (main) - Loaded the properties. Starting with the 'PROD' profile
[INFO ] 2024-04-25 11:37:36,905 de.rwth.idsg.steve.Application (main) - Date/time zone of the application is set to UTC. Current date/time: 2024-04-25T11:37:36.897Z
Log file: Not available
Starting.[INFO ] 2024-04-25 11:37:37,398 org.eclipse.jetty.server.Server (main) - jetty-10.0.14; built: 2023-02-22T23:12:32.272Z; git: 976721d0f3e903a243584d47870ad2f2c1bf9e55; jvm 17.0.11+9
.[INFO ] 2024-04-25 11:37:37,630 org.eclipse.jetty.server.handler.ContextHandler.steve (main) - No Spring WebApplicationInitializer types detected on classpath
[INFO ] 2024-04-25 11:37:37,682 org.eclipse.jetty.server.session.DefaultSessionIdManager (main) - Session workerName=node0
[INFO ] 2024-04-25 11:37:37,692 org.eclipse.jetty.server.handler.ContextHandler.steve (main) - Initializing Spring root WebApplicationContext
[INFO ] 2024-04-25 11:37:37,692 org.springframework.web.context.ContextLoader (main) - Root WebApplicationContext: initialization started
..[INFO ] 2024-04-25 11:37:38,901 com.zaxxer.hikari.HikariDataSource (main) - HikariPool-1 - Starting...
[INFO ] 2024-04-25 11:37:39,119 com.zaxxer.hikari.pool.HikariPool (main) - HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@5c59a0f7
[INFO ] 2024-04-25 11:37:39,120 com.zaxxer.hikari.HikariDataSource (main) - HikariPool-1 - Start completed.
..[INFO ] 2024-04-25 11:37:40,474 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean (main) - Creating Service {urn://Ocpp/Cs/2010/08/}CentralSystemService from class ocpp.cs._2010._08.CentralSystemService
.[INFO ] 2024-04-25 11:37:40,906 org.apache.cxf.endpoint.ServerImpl (main) - Setting the server's publish address to be /CentralSystemServiceOCPP12
[INFO ] 2024-04-25 11:37:40,918 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean (main) - Creating Service {urn://Ocpp/Cs/2012/06/}CentralSystemService from class ocpp.cs._2012._06.CentralSystemService
[INFO ] 2024-04-25 11:37:40,995 org.apache.cxf.endpoint.ServerImpl (main) - Setting the server's publish address to be /CentralSystemServiceOCPP15
[INFO ] 2024-04-25 11:37:40,996 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean (main) - Creating Service {urn://Ocpp/Cs/2015/10/}CentralSystemService from class ocpp.cs._2015._10.CentralSystemService
[INFO ] 2024-04-25 11:37:41,043 org.apache.cxf.endpoint.ServerImpl (main) - Setting the server's publish address to be /CentralSystemServiceOCPP16
[INFO ] 2024-04-25 11:37:41,048 org.apache.cxf.wsdl.service.factory.ReflectionServiceFactoryBean (main) - Creating Service {urn://Ocpp/Cs/2010/08/}CentralSystemService from class ocpp.cs._2010._08.CentralSystemService
[INFO ] 2024-04-25 11:37:41,058 org.apache.cxf.endpoint.ServerImpl (main) - Setting the server's publish address to be /CentralSystemService
..[WARN ] 2024-04-25 11:37:42,003 org.jooq.impl.DefaultExecuteContext.logVersionSupport (main) - Version mismatch         : Database version is older than what dialect MYSQL supports: 5.5.5-10.4.30-MariaDB-1:10.4.30+maria~ubu2004. Consider https://www.jooq.org/download/support-matrix to see what jOOQ version and edition supports which RDBMS versions.
.[INFO ] 2024-04-25 11:37:42,922 org.springframework.security.web.DefaultSecurityFilterChain (main) - Will secure any request with [org.springframework.security.web.session.DisableEncodeUrlFilter@3c84c32f, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@57ac220f, org.springframework.security.web.context.SecurityContextPersistenceFilter@11c68269, org.springframework.security.web.header.HeaderWriterFilter@511ba9c9, org.springframework.security.web.csrf.CsrfFilter@63d8590c, org.springframework.security.web.authentication.logout.LogoutFilter@2a1fce44, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@83b39c3, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@6018a6a2, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@5abf9a76, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@7e641005, org.springframework.security.web.session.SessionManagementFilter@5297030e, org.springframework.security.web.access.ExceptionTranslationFilter@5037f491, org.springframework.security.web.access.intercept.AuthorizationFilter@2ca4b010]
.[INFO ] 2024-04-25 11:37:42,986 org.hibernate.validator.internal.util.Version (main) - HV000001: Hibernate Validator 6.1.7.Final
[WARN ] 2024-04-25 11:37:43,449 de.rwth.idsg.steve.config.SecurityConfiguration (main) - Web APIs will not be exposed. Reason: 'webapi.key' and 'webapi.value' are not set in config file
[INFO ] 2024-04-25 11:37:43,491 org.springframework.security.web.DefaultSecurityFilterChain (main) - Will secure Ant [pattern='/api/**'] with [org.springframework.security.web.session.DisableEncodeUrlFilter@1548dc37, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@23317e8a, org.springframework.security.web.context.SecurityContextPersistenceFilter@657f1fc3, org.springframework.security.web.header.HeaderWriterFilter@42fe9099, org.springframework.security.web.authentication.logout.LogoutFilter@71b01319, de.rwth.idsg.steve.config.SecurityConfiguration$ApiKeyFilter@520c235f, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@6a0ca728, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@5cc088a8, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@3426d8e2, org.springframework.security.web.session.SessionManagementFilter@4437af21, org.springframework.security.web.access.ExceptionTranslationFilter@6a3cb81c, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@3c32f3d8]
[WARN ] 2024-04-25 11:37:43,495 org.springframework.security.config.annotation.web.builders.WebSecurity (main) - You are asking Spring Security to ignore Ant [pattern='/static/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
[INFO ] 2024-04-25 11:37:43,495 org.springframework.security.web.DefaultSecurityFilterChain (main) - Will not secure Ant [pattern='/static/**']
[WARN ] 2024-04-25 11:37:43,497 org.springframework.security.config.annotation.web.builders.WebSecurity (main) - You are asking Spring Security to ignore Ant [pattern='/services/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.
[INFO ] 2024-04-25 11:37:43,498 org.springframework.security.web.DefaultSecurityFilterChain (main) - Will not secure Ant [pattern='/services/**']
..[INFO ] 2024-04-25 11:37:44,642 org.springframework.web.context.ContextLoader (main) - Root WebApplicationContext initialized in 6950 ms
.[INFO ] 2024-04-25 11:37:44,767 org.eclipse.jetty.server.handler.ContextHandler.steve (main) - Initializing Spring DispatcherServlet 'spring-dispatcher'
[INFO ] 2024-04-25 11:37:44,767 org.springframework.web.servlet.DispatcherServlet (main) - Initializing Servlet 'spring-dispatcher'
[INFO ] 2024-04-25 11:37:44,768 org.springframework.web.servlet.DispatcherServlet (main) - Completed initialization in 1 ms
[INFO ] 2024-04-25 11:37:44,800 org.eclipse.jetty.server.handler.ContextHandler (main) - Started o.e.j.w.WebAppContext@6b5176f2{/steve,jar:file:/code/target/steve.jar!/webapp,AVAILABLE}
[INFO ] 2024-04-25 11:37:44,813 org.eclipse.jetty.server.AbstractConnector (main) - Started ServerConnector@734fca71{HTTP/1.1, (http/1.1)}{0.0.0.0:8180}
[INFO ] 2024-04-25 11:37:44,816 org.eclipse.jetty.server.Server (main) - Started Server@630cb4a4{STARTING}[10.0.14,sto=5000] @10859ms
 Done!
Hint: You can stop the application by pressing CTRL+C

Access the web interface using
- http://172.18.0.3:8180/steve/manager/home
SOAP endpoint for OCPP
- http://172.18.0.3:8180/steve/services/CentralSystemService
WebSocket/JSON endpoint for OCPP
- ws://172.18.0.3:8180/steve/websocket/CentralSystemService/(chargeBoxId)

```

therefore, unfortunately, i cannot reproduce and therefore cannot understand the following:

> Master is broken, just download the latest release.

master is apparently and factually not broken. i can also build the master without docker just fine. what makes you say that?

**Comment by goekay** [comment]
i was also able to access the web ui and login, and walk through the pages without issues.

**Comment by lokipo** [comment]
I should have looked at the changes between my original posts and today, sorry. As I was writing my original post I could not check out master and run it in docker, see the log above. I did then use the latest release, which worked. If this is fixed now: perfect.

**Comment by AffiTheCreator** [comment]
Hey guys , so i managed to get it working and the master is not broken. MY ISSUE, was vscode added Steve as a java project and kept auto compiling it somehow the files that ended up in the docker were somehow broken and caused the issue. 

Hope it saves times to anyone with the same problem

**Comment by goekay** [comment]
thanks, cool that is clarified. 

btw: we have github actions that build the project after a commit. if the action fails, i will know. and i will never will leave the master broken. if the build fails silently (or: build is fine, but there are runtime/behavioural problems), that is another story.

**Comment by lokipo** [comment]
Well, I guess I should really have checked before, sorry for that. Looks like master build fine in march but then refused to start due to some jetty version conflict.
I will mark this as closed.
