### ISSUE TITLE
Unexpected problem occured during version sanity check (Logging)

### ISSUE THREAD

**Issue by goekay** [steve-community/steve#900]
#### Checklist

- [x] I checked other issues already, but found no answer/solution
- [x] I checked the documentation and wiki, but found no answer/solution
- [x] I am running the latest version and the issue still occurs
- [x] I am sure that this issue is about SteVe (and not about the charging station software or something unrelated to SteVe)

#### Specifications
```
SteVe Version     : latest
Operating system  : does not matter
JDK               : does not matter
Database          : does not matter
```

#### Expected Behavior

normal logs.

#### Actual Behavior

error message (started with https://github.com/steve-community/steve/commit/334c117c5c56dcb7813a62df8025f21636a9c01e) + normal logs.

error message:
```
Unexpected problem occured during version sanity check
Reported exception:
java.lang.AbstractMethodError: Receiver class org.apache.logging.slf4j.SLF4JServiceProvider does not define or inherit an implementation of the resolved method 'abstract java.lang.String getRequestedApiVersion()' of interface org.slf4j.spi.SLF4JServiceProvider.
        at org.slf4j.LoggerFactory.versionSanityCheck(LoggerFactory.java:297)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:141)
        at org.slf4j.LoggerFactory.getProvider(LoggerFactory.java:421)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:407)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:356)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:382)
        at de.rwth.idsg.steve.Application.<clinit>(Application.java:31)

```

**Comment by goekay** [comment]
this is because of a bug (in the form of a typo) within the Log4j 2's new SLF4J impl. the method is called `getRequesteApiVersion()` instead of `getRequestedApiVersion()`

more: https://issues.apache.org/jira/browse/LOG4J2-3370:

**Comment by goekay** [comment]
is gone after https://github.com/steve-community/steve/pull/915
